### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by xTRam1** [STAR-Laboratory/Accelerating-RecSys-Training#2]
I am trying to recreate the results of the paper but whenever the training switches to the hot input training, I have a "device-side assert triggered" runtime-error. 
I am using Criteo Terabyte Dataset and ran the dlrm_input_profiler.py (512MB storage for hot embeddings and 5% input sampling) first and have the hot embedding dictionary, hot training data, and the normal training data as .npz files. I successfully trained the normal training data, but when the training switches to the hot training inputs, I receive this error for around 7000 lines:

`
/opt/conda/conda-bld/pytorch_1646756402876/work/aten/src/ATen/native/cuda/EmbeddingBag.cu:122: 
EmbeddingBag_updateOutputKernel_sum_mean: block: [1,0,0], thread: [31,5,0] 
Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
` 
This error message repeats for many lines with only the numbers in the `block: [1,0,0]` 
and `thread: [31, 5, 0]` changing. 

I did not change anything in the code and just ran the run_dlrm_fae.sh with the following arguments:
`
python dlrm_fae.py 	--arch-sparse-feature-size=64 \
						--arch-mlp-bot="13-512-256-64" \
						--arch-mlp-top="512-512-256-1" \
						--data-generation=dataset \
						--data-set=terabyte \
						--raw-data-file=./input/terabyte/day \
						--processed-data-file=./input/terabyte/terabyte_processed.npz \
						--train-hot-file=./input/terabyte_hot_cold/train_hot.npz \
						--train-normal-file=./input/terabyte_hot_cold/train_normal.npz \
						--hot-emb-dict-file=./input/terabyte_hot_cold/hot_emb_dict.npz \
						--loss-function=bce \
						--round-targets=True \
						--mini-batch-size=2048 \
						--print-freq=1024 \
						--test-freq=4096 \
						--test-mini-batch-size=2048 \
						--print-time \
						--save-model ./save_model/fea.pt \
						--load-model ./save_model/fea.pt \
						--plot-compute-graph
`

I tried searching for answers on the internet but couldn't solve the issue. I wanted to ask for you assistance. What do you think the issue may be?

For reference, I am using 4 NVIDIA TITAN RTX GPUs (24GB memory).

Thank you for your assistance. I am looking forward to your answer.

**Comment by madnan92** [comment]
Hi,

Would you please confirm exactly which version of torch are you using?
Also exactly which line of code gives you this error?

**Comment by Wangzesonga** [comment]
> Hi,
> 
> Would you please confirm exactly which version of torch are you using? Also exactly which line of code gives you this error?

I met the same problem, when I trained the hot input, the errors came out:

Traceback (most recent call last):
  File "dlrm_fae.py", line 1429, in <module>
    Z = dlrm_wrap(X, lS_o, lS_i, use_gpu, device, data)
  File "dlrm_fae.py", line 953, in dlrm_wrap
    return dlrm(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "dlrm_fae.py", line 390, in forward
    return self.parallel_forward(dense_x, lS_o, lS_i)
  File "dlrm_fae.py", line 518, in parallel_forward
    zk = self.interact_features(x[k], ly[k])
  File "dlrm_fae.py", line 372, in interact_features
    Zflat = Z[:, li, lj]
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

My build environment:

cpu_info: Intel(R) Xeon(R) Gold 5320 CPU @ 2.20GHz
gpu_info: NVIDIA Tesla V100 32GB PCIe
memory: Samsung DDR4 512G
cuda: "11.6"
python:3.8.10
pytorch:1.13
nvidia-driver:510.108.03
Ubuntu:20.04.5

**Comment by madnan92** [comment]
Please re-run the profiling and then run dlrm_fae.py.
We have fixed hot embedding indices that were giving Cuda device side assertion.
